name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'sub-project/pom.xml' # optional
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload artefact
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: target/*.jar
          retention-days: 2
  build-docker-image-push:
    runs-on: ubunut-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
            name: Package
            path: target

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
        run: |
          docker build . -t ghcr.io/${{ github.repository }}:main
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main   password: ${{ secrets.GITHUB_TOKEN }}